In [1]:
from net import Petri

env = Petri(csv_path='N1p21t16.CSV', n_t=16)



In [45]:
env.reset()
env.m

array([13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  2,  2])

In [19]:
import numpy as np
s1 = [0,1,2,3,4,5]
s2 = [0,1,2,15]
#撤离
s3 = np.arange(6,14)
s4 = [14,9,10,11,12,13]

In [20]:
s3

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [50]:
for _ in range(2):
    for t in s1:
        _,_,_,_,_,info = env.step(t)
print(info["time"])
print(env.m)
for t in s2:
        _,_,_,_,_,info = env.step(t)
print(info["time"])
print(env.m)


7230
[ 1  0  0  0  0  0  2  0  0  0  0  0  0  0 10  0  1  1  1  2  2]
7254
[ 0  0  0  0  0  0  2  0  0  0  0  0  0  0 10  1  1  1  1  2  2]


In [51]:
for _ in range(2):
    for t in s3:
        _,_,_,_,_,info = env.step(t)
print(info["time"])
print(env.m)
for t in s4:
        _,_,_,_,_,info = env.step(t)
print(info["time"])
print(env.m)

10283
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  1  1  1  1  2  2]
10418
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 13  0  1  1  1  2  2]


In [ ]:
for _ in range(2):
    for t in s3:
        _,_,_,_,_,info = env.step(t)
print(info["time"])
print(env.m)